server:
  port: 8081
  shutdown: graceful
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    info:
      git:
        mode: full
        exposed: true
        properties:
          mode: full
          exposed: true

spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
    show-sql: true

catalog:
  page-size: 10