server:
  port: 8082
  shutdown: graceful
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    info:
      git:
        mode: full
        exposed: true
        properties:
          mode: full
          exposed: true

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

orders:
  order-events:
    exchange: order-exchange
  new-orders:
    queue: new-orders
  delivered-orders:
    queue: delivered-orders
  cancelled-orders:
    queue: cancelled-orders
  error-orders:
    queue: error-orders

order:
  page-size: 10